### ISSUE TITLE
Exporting next/prev link metadata

### ISSUE THREAD

**Issue by weaverryan** [weaverryan/symfony-docs#5]
There is a problem with next/prev links when generating the JSON files: there is presently
no way to get the meta info of the prev/next from the metas of a current file

**Comment by nikophil** [comment]
actually, we're getting the prev / next from toc tree in the meta of the parent file.
The problem is that in the toc, the files are referenced by their short name, but the "key" to grab a meta is constructed with the long name (the absolute path of the rst file)
